/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.senai.view;

import br.senai.controller.AulaController;
import br.senai.model.Aula;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author bruno_andrade
 */
public class ConsultaAulaUI extends javax.swing.JInternalFrame {

    boolean controleAula;
    AulaController aulaController;
    private ArrayList<Aula> listaAula;

    /**
     * Creates new form PesquisarAula
     *
     * @param controle
     */
    public ConsultaAulaUI(boolean controle) {
        initComponents();
        checkAtivo.setSelected(true);
        this.controleAula = controle;
        if (this.controleAula) {
            btnAlterar.setText("Selecionar");
            btnNovo.setVisible(false);
        }
        atualizarTabelaAula();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableAulas = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        cbxDiaSemana = new javax.swing.JComboBox();
        txtNomeProfessor = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        checkAtivo = new javax.swing.JCheckBox();
        btnAlterar = new javax.swing.JButton();
        btnNovo = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Pesquisa de Aulas");

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        tableAulas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Nome do Professor", "Dia da Semana", "Hora Inicial", "Hora Final", "Qtd. Alunos", "Status"
            }
        ));
        jScrollPane1.setViewportView(tableAulas);

        jLabel2.setText("Pesquisar:");

        cbxDiaSemana.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione um dia", "Segunda-Feira", "Terça-Feira", "Quarta-Feira", "Quinta-Feira", "Sexta-Feira", "Sábado", "Domingo" }));

        jLabel3.setText("Nome do Professor: ");

        jLabel4.setText("Selecione dia da Semana: ");

        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Find.png"))); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/edit-clear.png"))); // NOI18N
        btnLimpar.setText("Limpar");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        jLabel5.setText("Somente Ativos: ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbxDiaSemana, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtNomeProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(checkAtivo)
                                .addGap(109, 109, 109))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(btnBuscar)
                                .addGap(18, 18, 18)
                                .addComponent(btnLimpar)
                                .addContainerGap())))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNomeProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(checkAtivo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cbxDiaSemana, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar)
                    .addComponent(btnLimpar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        btnAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/gtk_edit.png"))); // NOI18N
        btnAlterar.setText("Alterar");
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        btnNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/add.png"))); // NOI18N
        btnNovo.setText("Novo");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cancel.png"))); // NOI18N
        btnCancelar.setText("Cancelar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnNovo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAlterar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancelar))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNovo)
                    .addComponent(btnAlterar)
                    .addComponent(btnCancelar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        int linhaSelecionada = tableAulas.getSelectedRow();
        if (linhaSelecionada == -1) {
            JOptionPane.showMessageDialog(null, "Selecione uma Aula");
        } else {
            Aula aula = new Aula();
            try {
                for (int i = 0; i < listaAula.size(); i++) {
                    if (tableAulas.getSelectedRow() == i) {
                        aula = this.listaAula.get(i);
                        break;
                    }
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e.getMessage());
            }

            if (this.controleAula) {
                AulaController.obterInstancia().preencheFormAluno(aula);
                this.dispose();
            } else {
                CadastroAulaUI cadatroAula = new CadastroAulaUI(aula);
                cadatroAula.setVisible(true);
                FormPrincipal.getPainelPrincipal().add(cadatroAula);
                this.hide();
                //this.dispose();
                //Função de alteração do professor        
            }
            tableAulas.getSelectedRow();
            atualizarTabelaAula();
        }
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        aulaController = new AulaController();
        Integer status = 0;
        Integer day = cbxDiaSemana.getSelectedIndex();
        if (checkAtivo.isSelected()) {
            status = 1;
        } else {
            status = 0;
        }
        atualizarTabelaAula(aulaController.getAulaPesquisa(txtNomeProfessor.getText().toString(), day, status));
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        try {
            aulaController = new AulaController();
            CadastroAulaUI cadAula = new CadastroAulaUI(null);
            this.hide();
            cadAula.show();
            FormPrincipal.getPainelPrincipal().add(cadAula);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Tente novamente.");
        }
    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        limparTela();
        atualizarTabelaAula();
    }//GEN-LAST:event_btnLimparActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnNovo;
    private javax.swing.JComboBox cbxDiaSemana;
    private javax.swing.JCheckBox checkAtivo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableAulas;
    private javax.swing.JTextField txtNomeProfessor;
    // End of variables declaration//GEN-END:variables

    private void atualizarTabelaAula() {
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.setColumnIdentifiers(new String[]{"Nome do Professor", "Dia da Semana", "Hora Inicial", "Hora Final", "Qnd. Alunos", "Status"});
        this.listaAula = AulaController.obterInstancia().listarTodos();
        for (int i = 0; i < this.listaAula.size(); i++) {
            String dia = "";
            String status = "";
            if (this.listaAula.get(i).getDiaSemana() == 1) {
                dia = "Seg.";
            } else if (this.listaAula.get(i).getDiaSemana() == 2) {
                dia = "Ter.";
            } else if (this.listaAula.get(i).getDiaSemana() == 3) {
                dia = "Qua.";
            } else if (this.listaAula.get(i).getDiaSemana() == 4) {
                dia = "Qui.";
            } else if (this.listaAula.get(i).getDiaSemana() == 5) {
                dia = "Sex";
            } else if (this.listaAula.get(i).getDiaSemana() == 6) {
                dia = "Sáb.";
            } else if (this.listaAula.get(i).getDiaSemana() == 7) {
                dia = "Dom.";
            }
            if (this.listaAula.get(i).getStatus() == 0) {
                status = "Inativo";
            } else {
                status = "Ativo";
            }

            modelo.addRow(new Object[]{this.listaAula.get(i).getProfessor().getDscNome(),
                dia,
                this.listaAula.get(i).gethInicio(),
                this.listaAula.get(i).gethFim(),
                this.listaAula.get(i).getNumeroAlunos(),
                status});
        }
        tableAulas.setModel(modelo);
    }

    private void atualizarTabelaAula(ArrayList<Aula> aulaPesquisa) {
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.setColumnIdentifiers(new String[]{"Nome do Professor", "Dia da Semana", "Hora Inicial", "Hora Final", "Qnd. Alunos", "Status"});
        for (int i = 0; i < aulaPesquisa.size(); i++) {
            String dia = "";
            String status = "";
            if (aulaPesquisa.get(i).getDiaSemana() == 1) {
                dia = "Seg.";
            } else if (aulaPesquisa.get(i).getDiaSemana() == 2) {
                dia = "Ter.";
            } else if (aulaPesquisa.get(i).getDiaSemana() == 3) {
                dia = "Qua.";
            } else if (aulaPesquisa.get(i).getDiaSemana() == 4) {
                dia = "Qui.";
            } else if (aulaPesquisa.get(i).getDiaSemana() == 5) {
                dia = "Sex";
            } else if (aulaPesquisa.get(i).getDiaSemana() == 6) {
                dia = "Sáb.";
            } else if (aulaPesquisa.get(i).getDiaSemana() == 7) {
                dia = "Dom.";
            }
            if (aulaPesquisa.get(i).getStatus() == 0) {
                status = "Inativo";
            } else {
                status = "Ativo";
            }

            modelo.addRow(new Object[]{aulaPesquisa.get(i).getProfessor().getDscNome(),
                dia,
                aulaPesquisa.get(i).gethInicio(),
                aulaPesquisa.get(i).gethFim(),
                aulaPesquisa.get(i).getNumeroAlunos(),
                status});
        }
        tableAulas.setModel(modelo);
    }

    private void limparTela() {
        txtNomeProfessor.setText("");
        cbxDiaSemana.setSelectedIndex(0);
        checkAtivo.setSelected(true);
    }
}
