/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.senai.view;

import br.senai.controller.ProfessorController;
import br.senai.model.Professor;
import br.senai.model.RelatorioProfAula;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Andrade
 */
public class RelatorioAulaProfessor extends javax.swing.JInternalFrame {

    ArrayList<Professor> listaProf = ProfessorController.obterInstancia().listarTodos();
    private ArrayList<RelatorioProfAula> listaProfAula;

    /**
     * Creates new form RelatorioAulaProfessor
     */
    public RelatorioAulaProfessor() {
        initComponents();
        carregarCombos();
    }

    private void carregarCombos() {
        DefaultComboBoxModel modeloProf = new DefaultComboBoxModel();
        for (int i = 0; i < this.listaProf.size(); i++) {
            modeloProf.addElement(this.listaProf.get(i).getDscNome());
        }
        cbxProfessor.setModel(modeloProf);
        cbxProfessor.setSelectedIndex(-1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        cbxProfessor = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableProfAula = new javax.swing.JTable();
        btnLimpar = new javax.swing.JButton();
        btnFechar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Relatório Aula por Professor");

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setText("Professor: ");

        cbxProfessor.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbxProfessor.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxProfessorItemStateChanged(evt);
            }
        });

        tableProfAula.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Professor", "Hora Inicio", "Hora Final", "Dia da Semana", "Qnt. Alunos/Aula", "Qnt. Alunos Matr.", "Status Aula"
            }
        ));
        jScrollPane1.setViewportView(tableProfAula);

        btnLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/edit-clear.png"))); // NOI18N
        btnLimpar.setText("Limpar");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbxProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(97, 97, 97)
                        .addComponent(btnLimpar)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbxProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLimpar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnFechar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cancel.png"))); // NOI18N
        btnFechar.setText("Cancelar");
        btnFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 438, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnFechar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnFechar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbxProfessorItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxProfessorItemStateChanged

        if (cbxProfessor.getSelectedIndex() > -1) {
            atualizarTabela(cbxProfessor.getSelectedItem().toString());
        }
    }//GEN-LAST:event_cbxProfessorItemStateChanged

    private void btnFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnFecharActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.setColumnIdentifiers(new String[]{"Professor", "Hora Inicio", "Hora Final", "Dia da Semana", "Qnt. Alunos/Aula", "Qnt. Alunos Matr.", "Status Aula"});
        modelo.addRow(new Object[]{"", "", "", "", "", ""});
        tableProfAula.setModel(modelo);
        cbxProfessor.setSelectedIndex(-1);
    }//GEN-LAST:event_btnLimparActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFechar;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JComboBox cbxProfessor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableProfAula;
    // End of variables declaration//GEN-END:variables

    private void atualizarTabela(String profName) {
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.setColumnIdentifiers(new String[]{"Professor", "Hora Inicio", "Hora Final", "Dia da Semana", "Qnt. Alunos/Aula", "Qnt. Alunos Matr.", "Status Aula"});
        this.listaProfAula = ProfessorController.obterInstancia().listarRelatorioAula(profName);
        for (int i = 0; i < this.listaProfAula.size(); i++) {
            String status = "";
            String dia = "";
            if (this.listaProfAula.get(i).getDiaSemana() == 1) {
                dia = "Seg.";
            } else if (this.listaProfAula.get(i).getDiaSemana() == 2) {
                dia = "Ter.";
            } else if (this.listaProfAula.get(i).getDiaSemana() == 3) {
                dia = "Qua.";
            } else if (this.listaProfAula.get(i).getDiaSemana() == 4) {
                dia = "Qui.";
            } else if (this.listaProfAula.get(i).getDiaSemana() == 5) {
                dia = "Sex";
            } else if (this.listaProfAula.get(i).getDiaSemana() == 6) {
                dia = "Sáb.";
            } else if (this.listaProfAula.get(i).getDiaSemana() == 7) {
                dia = "Dom.";
            }
            if (this.listaProfAula.get(i).getStatus() == 0) {
                status = "Inativo";
            } else {
                status = "Ativo";
            }

            modelo.addRow(new Object[]{this.listaProfAula.get(i).getNomeProf(),
                this.listaProfAula.get(i).getHrInicio(),
                this.listaProfAula.get(i).getHrFinal(),
                dia,
                this.listaProfAula.get(i).getQntNumAluno(),
                this.listaProfAula.get(i).getNumAlunoAula(),
                status});
        }
        tableProfAula.setModel(modelo);
    }
}
