/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.senai.view;

import br.senai.controller.AlunoController;
import br.senai.controller.AulaController;
import br.senai.controller.ProfessorController;
import br.senai.model.Aluno;
import br.senai.model.Aula;
import br.senai.model.Professor;
import br.senai.model.RelatorioProfAula;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Andrade
 */
public class RelatorioAulaAlunoSemana extends javax.swing.JInternalFrame {

    /**
     * Creates new form RelatorioAulaProfessor
     */
    public RelatorioAulaAlunoSemana() {
        initComponents();
        jRadioButtonNome.setSelected(true);
        jRadioButtonCPF.setSelected(false);
        jTextFieldCPF.setEnabled(false);
        atualizarTabela(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableProfAula = new javax.swing.JTable();
        btnLimpar = new javax.swing.JButton();
        jButton1Buscar = new javax.swing.JButton();
        jRadioButtonNome = new javax.swing.JRadioButton();
        jRadioButtonCPF = new javax.swing.JRadioButton();
        javax.swing.text.MaskFormatter maskCPFAluno = null;
        try{
            maskCPFAluno= new javax.swing.text.MaskFormatter("###.###.###-##");
            maskCPFAluno.setPlaceholderCharacter('_');

        }
        catch (java.text.ParseException exc) {}
        jTextFieldCPF = new javax.swing.JFormattedTextField(maskCPFAluno);
        jTextFieldNome = new javax.swing.JTextField();
        btnFechar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Relatório Aluno (Aulas/Semana)");

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        tableProfAula.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Aluno", "Domingo", "Segunda", "Terça", "Quarta", "Quinta", "Sexta", "Sábado"
            }
        ));
        jScrollPane1.setViewportView(tableProfAula);

        btnLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/edit-clear.png"))); // NOI18N
        btnLimpar.setText("Limpar");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        jButton1Buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Find.png"))); // NOI18N
        jButton1Buscar.setText("Buscar");
        jButton1Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1BuscarActionPerformed(evt);
            }
        });

        jRadioButtonNome.setText("Nome");
        jRadioButtonNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonNomeActionPerformed(evt);
            }
        });

        jRadioButtonCPF.setText("CPF");
        jRadioButtonCPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonCPFActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jRadioButtonCPF)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldCPF))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jRadioButtonNome)
                                .addGap(10, 10, 10)
                                .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(51, 51, 51)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton1Buscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnLimpar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jRadioButtonNome)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton1Buscar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jRadioButtonCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextFieldCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnLimpar, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        btnFechar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cancel.png"))); // NOI18N
        btnFechar.setText("Cancelar");
        btnFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnFechar))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 616, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnFechar)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnFecharActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        jTextFieldNome.setText("");
        jTextFieldCPF.setText("");
        atualizarTabela(null);
    }//GEN-LAST:event_btnLimparActionPerformed

    private void jButton1BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1BuscarActionPerformed
        AlunoController contAluno = new AlunoController();
        String coluna = "";
        String texto = "";
        if (jRadioButtonCPF.isSelected()) {
            coluna = "dsc_CPF";
            texto = jTextFieldCPF.getText().toString().replace("-", "").replace(".", "").replace("_", "");
        } else if (jRadioButtonNome.isSelected()) {
            coluna = "dsc_Nome";
            texto = jTextFieldNome.getText().toString();
        }
        atualizarTabela(contAluno.getAlunoPesquisa(coluna, texto, 1));
    }//GEN-LAST:event_jButton1BuscarActionPerformed

    private void jRadioButtonNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonNomeActionPerformed
        jTextFieldNome.setEnabled(true);
        jTextFieldCPF.setEnabled(false);
        jRadioButtonCPF.setSelected(false);
        jTextFieldCPF.setText("");

    }//GEN-LAST:event_jRadioButtonNomeActionPerformed

    private void jRadioButtonCPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonCPFActionPerformed
        jTextFieldCPF.setEnabled(true);
        jTextFieldNome.setEnabled(false);
        jRadioButtonNome.setSelected(false);
        jTextFieldNome.setText("");
    }//GEN-LAST:event_jRadioButtonCPFActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFechar;
    private javax.swing.JButton btnLimpar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton1Buscar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButtonCPF;
    private javax.swing.JRadioButton jRadioButtonNome;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextFieldCPF;
    private javax.swing.JTextField jTextFieldNome;
    private javax.swing.JTable tableProfAula;
    // End of variables declaration//GEN-END:variables

    private void atualizarTabela(ArrayList<Aluno> listaAluno) {
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.setColumnIdentifiers(new String[]{"Aluno", "Domingo", "Segunda", "Terça", "Quarta", "Quinta", "Sexta", "Sabado"});

        if (listaAluno == null) {
            listaAluno = AlunoController.obterInstancia().listarTodos();
        }

        for (Aluno aluno : listaAluno) {
            ArrayList<Aula> listaAula = AlunoController.obterInstancia().listarTodasAulasPorAluno(aluno.getId());

            String horarioAulaDomingo = "";
            String horarioAulaSegunda = "";
            String horarioAulaTerca = "";
            String horarioAulaQuarta = "";
            String horarioAulaQuinta = "";
            String horarioAulaSexta = "";
            String horarioAulaSabado = "";

            for (Aula aula : listaAula) {
                if (aula.getDiaSemana() == 1) {
                    horarioAulaSegunda = aula.gethInicio() + "-" + aula.gethFim();
                } else if (aula.getDiaSemana() == 2) {
                    horarioAulaTerca = aula.gethInicio() + "-" + aula.gethFim();
                    // verificar se existe mais de uma aula no mesmo dia
                } else if (aula.getDiaSemana() == 3) {
                    horarioAulaQuarta = aula.gethInicio() + "-" + aula.gethFim();
                    // verificar se existe mais de uma aula no mesmo dia
                } else if (aula.getDiaSemana() == 4) {
                    horarioAulaQuinta = aula.gethInicio() + "-" + aula.gethFim();
                    // verificar se existe mais de uma aula no mesmo dia
                } else if (aula.getDiaSemana() == 5) {
                    horarioAulaSexta = aula.gethInicio() + "-" + aula.gethFim();
                    // verificar se existe mais de uma aula no mesmo dia
                } else if (aula.getDiaSemana() == 6) {
                    horarioAulaSabado = aula.gethInicio() + "-" + aula.gethFim();
                    // verificar se existe mais de uma aula no mesmo dia
                } else if (aula.getDiaSemana() == 7) {
                    horarioAulaDomingo = aula.gethInicio() + "-" + aula.gethFim();
                    // verificar se existe mais de uma aula no mesmo dia
                }

            }

            modelo.addRow(new Object[]{aluno.getDscNome(),
                horarioAulaDomingo,
                horarioAulaSegunda,
                horarioAulaTerca,
                horarioAulaQuarta,
                horarioAulaQuinta,
                horarioAulaSexta,
                horarioAulaSabado});
        }
        tableProfAula.setModel(modelo);
    }

}

                        //} else {
                        //  horarioAulaSegunda += ", " +aula.gethInicio()+ "-"+ aula.gethFim();